### ISSUE TITLE
 KCRW's 24/7 streams (both news & music to be played via command line args

### ISSUE THREAD

**Issue by justinpage** [hulbert/node-kcrw#2]
## Proposal

I would like to add this feature to the app. Wanted to verify the main edge cases:
- `kcrw`: will default to what is currently live on stream (e.g. garth trinidad)
- `kcrw news` will play News 24
- `kcrw eclectic` will play Eclectic 24
- `kcrw <non-supported-arg>`: will default to `kcrw` argument
- `kcrw <supported-argument> <non-supported-arg>...` will default to `kcrw` argument
## Execution

Going to implement Standard Method library and then use that to define:

```
var STREAM_URL = 'http://kcrw.ic.llnwd.net/stream/kcrw_live';
var CURRENT_TRACK_URL = 'http://tracklist-api.kcrw.com/Simulcast';
var NOW_PLAYING_URL = 'http://www.kcrw.com/now_playing.json';
```

Time to snoop the source on http://kcrw.com (headers that is).

**Comment by hulbert** [comment]
This looks good to me. If we want to be a bit more full-featured would be okay with introducing `yargs` as a dependency so we can get easy `-h`/`--help` flag handling and auto documentation of commands.

**Comment by justinpage** [comment]
"Yargs be a node.js library fer hearties tryin' ter parse optstrings." -definitely a cool feature. Let's use it.

**Comment by justinpage** [comment]
I'll set aside some time this weekend to play with.

**Comment by hulbert** [comment]
I added hacky support for eclectic24 in this commit 659846e2b3a9b0e1457677f64cf4e4a076db13a3
